#include "BinCode.h"

int main() {
    setlocale(LC_ALL, "Russian");
    int dec;
    cout << "Введите десятичное число: ";
    cin >> dec;
    Bin binary = Dec_To_Pryam(dec);
    Cout_Bin(binary);
    cout << endl;
    Cout_Bin(Pryam_To_Obratn(binary));
    cout << endl;
    Cout_Bin(Pryam_To_Dopoln(binary));
    cout << endl;
    cout << endl;
    int dec1, dec2;
    cout << "Сумма: " << endl;
    cout << "Введите первое число: ";
    cin >> dec1;
    cout << "Ведите второе число: ";
    cin >> dec2;
    Bin bin1 = Dec_To_Pryam(dec1);
    Bin bin2 = Dec_To_Pryam(dec2);
    Bin bin3 = Bin_Sum(Pryam_To_Dopoln(bin1), Pryam_To_Dopoln(bin2));
    Cout_Bin(bin3);
    cout << endl;
    bin3 = Dopoln_To_Pryam(bin3);
    Cout_Bin(bin3);
    double int3 = Pryam_To_Dec(bin3);
    cout << endl << "Десятичный формат: " << int3 << endl;
    cout << endl;
    cout << "Умножение: " << endl;
    cout << "Введите первое число: ";
    cin >> dec1;
    cout << "Ведите второе число: ";
    cin >> dec2;
    Bin bin11 = Dec_To_Pryam(dec1);
    Bin bin12 = Dec_To_Pryam(dec2);
    Bin bin13 = Bin_Multiply(bin11,bin12);
    Cout_Bin(bin13);
    double int13 = Pryam_To_Dec(bin13);
    cout << endl << "Десятичный формат: " << int13 << endl;
    cout << endl << "Деление: " << endl;
    cout << "Введите делимое: ";
    cin >> dec1;
    cout << "Ведите делитель: ";
    cin >> dec2;
    Bin bin21 = Dec_To_Pryam(dec1);
    Bin bin22 = Dec_To_Pryam(dec2);
    Bin bin23 = Devide_Bin(bin21, bin22);
    Cout_Bin(bin23);
    double int23 = Pryam_To_Dec(bin23);
    cout << endl << "Десятичный формат: " << int23 << endl;
    cout << endl << "Плавающая точка: " << endl << "Введите дробное число: " << endl;
    double dec4;
    cin >> dec4;
    Bin bin4 = Double_To_Plav(dec4);
    Cout_Bin(bin4);
    cout << endl << "Сложение с плавающей точкой: " << endl;
    cout << "Введите первое число: ";
    double dec51;
    cin >> dec51;
    cout << "Введите второе число: ";
    double dec52;
    cin >> dec52;
    Bin bin51 = Double_To_Plav(dec51);
    Bin bin52 = Double_To_Plav(dec52);
    Bin bin53 = Plav_Bin_Sum(bin51, bin52);
    Cout_Bin(bin53);
    double int53 = Pryam_To_Dec(Plav_To_Pryam(bin53));
    cout << endl << "Десятичный формат: " << int53;
    return 0;
}